name: Update Profile README stats
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - main

jobs:
  github-profile-summary:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      # https://github.com/lowlighter/metrics
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/reactions/README.md
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/calendar/README.md
          plugin_calendar: yes
          plugin_calendar_limit: 3

      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Commit back
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Update snake

          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          # branch: feature-123

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          # commit_options: "--no-verify --signoff"

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: "dist/*.svg"

          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: .

          # Optional commit user and author settings
          # commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          # commit_author: Author <actions@github.com> # defaults to "username <username@users.noreply.github.com>", where "username" belongs to the author of the commit that triggered the run

          # Optional. Tag name being created in the local repository and
          # pushed to remote repository and defined branch.
          # tagging_message: "v1.0.0"

          # Optional. Option used by `git-status` to determine if the repository is
          # dirty. See https://git-scm.com/docs/git-status#_options
          # status_options: "--untracked-files=no"

          # Optional. Options used by `git-add`.
          # See https://git-scm.com/docs/git-add#_options
          # add_options: "-u"

          # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          # push_options: "--force"

          # Optional. Disable dirty check and always try to create a commit and push
          # skip_dirty_check: true

          # Optional. Skip internal call to `git fetch`
          # skip_fetch: true

          # Optional. Skip internal call to `git checkout`
          # skip_checkout: true

          # Optional. Prevents the shell from expanding filenames.
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          # disable_globbing: true

          # Optional. Create given branch name in local and remote repository.
          # create_branch: true
